version: '3'
services:
  backend:
    build: ./backend
    ports:
      - '3000:3000'
    depends_on:
      - postgres_db
    environment:
      PGUSER: postgres
      PGHOST: postgres
      PGDATABASE: EcommerceDB
      PGPASSWORD: password1234
      PGPORT: 5432
    volumes:
      - backend_data:/app/data
    networks:
      - ecommerce_network

  frontend:
    build: ./frontend
    ports:
      - '5173:5173'
    volumes:
      - frontend_data:/app/data
    networks:
      - ecommerce_network

  postgres_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password1234
      POSTGRES_DB: EcommerceDB
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ecommerce_network

networks:
  ecommerce_network:
    driver: bridge

volumes:
  backend_data:
  frontend_data:
  postgres_data: